# Generated by Django 4.2.7 on 2024-01-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isApp', '0003_post_img_chatdetection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatDetection',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
