# Generated by Django 4.2.7 on 2024-04-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isApp', '0005_chat_post_feedback_detection_comments_chatdetection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.users')),
            ],
        ),
    ]
