# Generated by Django 4.2.7 on 2025-04-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isApp', '0006_commentdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blockedBy',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='canChat',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.commentdetection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.users')),
            ],
        ),
    ]
