# Generated by Django 4.2.7 on 2025-04-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isApp', '0007_chat_blockedby_chat_canchat_commentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.comments'),
        ),
    ]
