# Generated by Django 4.2.7 on 2025-04-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isApp', '0008_alter_commentreport_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isApp.users')),
            ],
        ),
    ]
